{
 "title": "Kubernetes Volumes",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pvc",
    "label": "PVC",
    "query": {
     "query": "label_values(persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WARNING! Experimental Dashboard. Expand to read more.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Experimental Dashboard",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "## Disclaimer \n\nThis Experimental Dashboard is not a part of the official Percona Monitoring and Management (PMM) deployment and might be updated. \nWe ship this Dashboard to obtain feedback from our users. \n\nOnce we officially release this Dashboard, it will be moved to the appropriate folder. \n\n## About Dashboard\n\nThis Dashboard is a part of the [DBaaS solution](https://www.percona.com/doc/percona-monitoring-and-management/2.x/using/dbaas.html) in PMM.\nThis Dashboard displays the resource consumption in the K8s Cluster.\n\nTo provide feedback on the Dashboard, visit [our forum](https://forums.percona.com/c/percona-monitoring-and-management-pmm/pmm-unofficial-dashboards-and-plugins/67)."
     }
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Volume Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"}",
     "legendFormat": "{{namespace}} - {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Volume Used %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"}) by (persistentvolumeclaim)\n  /\nsum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{namespace}} {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Volume Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"}",
     "legendFormat": "{{namespace}} - {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Volume IO Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"}[$interval])",
     "legendFormat": "{{namespace}} - {{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}