{
 "title": "Pods Improved",
 "description": "An improved kubernetes pod resource usage view that scales horizontally for side-by-side comparison",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_labels, node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_last_seen{node=~\"$node\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_last_seen{node=~\"$node\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_last_seen{node=~\"$node\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$pod",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "pod",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}[5m])) by (pod,container,namespace,node) / sum(kube_pod_container_resource_limits{resource=\"cpu\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}) by (pod,container,namespace,node)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage Seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}[5m])) by (pod,container,namespace,node)",
     "legendFormat": "{{container}} - usage"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}",
     "legendFormat": "{{container}} - limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}",
     "legendFormat": "{{container}} - request"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}[5m])) by (pod, container, namespace, node)",
     "legendFormat": "{{container}} - throttled"
    }
   ]
  },
  {
   "title": "Throttled Seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}[5m])) by (pod, container, namespace, node)",
     "legendFormat": "{{container}} - cpus"
    }
   ]
  },
  {
   "title": "Periods [5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}[5m])) by (pod, container, namespace, node)",
     "legendFormat": "throttled - {{container}}"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_periods_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}[5m])) by (pod, container, namespace, node)",
     "legendFormat": "periods - {{container}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}) by (pod,container,namespace,node) / sum(kube_pod_container_resource_limits{resource=\"memory\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}) by (pod,container,namespace,node)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}) by (pod,container,namespace,node)",
     "legendFormat": "{{container}} - usage"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}",
     "legendFormat": "{{container}} - limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}",
     "legendFormat": "{{container}} - request"
    },
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}[5m])"
    }
   ]
  },
  {
   "title": "Memory Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}",
     "legendFormat": "{{container}} - rss"
    },
    {
     "expr": "container_memory_swap{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}",
     "legendFormat": "{{container}} - swap"
    },
    {
     "expr": "container_memory_working_set_bytes{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}",
     "legendFormat": "{{container}} - working set"
    },
    {
     "expr": "container_memory_cache{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}",
     "legendFormat": "{{container}} - cache"
    },
    {
     "expr": "container_memory_mapped_file{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}",
     "legendFormat": "{{container}} - mapped file"
    },
    {
     "expr": "container_memory_max_usage_bytes{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}",
     "legendFormat": "{{container}} - max usage"
    },
    {
     "expr": "container_memory_usage_bytes{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\", container=~\"$container\"}",
     "legendFormat": "{{container}} - usage"
    }
   ]
  }
 ]
}