{
 "title": "Portworx Volume Status",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "volumeid",
    "label": "VolumeID",
    "query": {
     "query": "label_values(px_volume_usage_bytes,volumeid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PX Volume Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Usage Status",
   "type": "table-old",
   "gridPos": { "h": 22, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(px_volume_usage_bytes/px_volume_capacity_bytes)*100",
     "legendFormat": "volumeid - {{volumeid}}"
    }
   ]
  },
  {
   "title": "Volume Sizes",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "px_volume_capacity_bytes",
     "legendFormat": "volumeid - {{volumeid}} - on - {{host}}}"
    }
   ]
  },
  {
   "title": "Volume HA Level",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 1 },
   "targets": [
    { "expr": "px_volume_halevel", "legendFormat": "volumeid - {{volumeid}}" }
   ]
  },
  {
   "title": "Volume Depth IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "px_volume_depth_io{volumeid=~\"$volumeid\"}",
     "legendFormat": "{{volumeid}}"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(px_volume_usage_bytes/px_volume_capacity_bytes)*100",
     "legendFormat": "{{volumeid}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  { "title": "Volume Write Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Volume Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "px_volume_latency_seconds{volumeid=~\"$volumeid\"}",
     "legendFormat": "{{volumeid}}"
    }
   ]
  },
  {
   "title": "Volume Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(px_volume_iops{volumeid=~\"$volumeid\"}[5m])",
     "legendFormat": "{{volumeid}}"
    }
   ]
  },
  { "title": "Volume Read Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Volume Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    {
     "format": "bytes",
     "label": "Bytes/second read (-) / write (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(px_volume_writethroughput{volumeid=~\"$volumeid\"}[5m]) ",
     "legendFormat": "{{volumeid}}_writethroughput"
    },
    {
     "expr": "irate(px_volume_readthroughput{volumeid=~\"$volumeid\"}[5m])",
     "legendFormat": "{{volumeid}}_readthroughput"
    }
   ]
  },
  {
   "title": "Volume IOs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    { "expr": "irate(px_volume_iops[5m]) ", "legendFormat": "{{volumeid}}_iops" }
   ]
  }
 ]
}