{
 "title": "Portworx Volume Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "volumeid",
    "label": "VolumeID",
    "query": {
     "query": "label_values(px_volume_usage_bytes,volumeid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PX Volume Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Sizes",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "px_volume_capacity_bytes", "legendFormat": "{{volumename}}" }
   ]
  },
  {
   "title": "Volume Usage Status",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(px_volume_usage_bytes/px_volume_capacity_bytes)*100",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume HA Level",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "targets": [
    { "expr": "px_volume_halevel", "legendFormat": "{{volumename}}" }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Volume IO Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "px_volume_depth_io{volumeid=~\"$volumeid\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(px_volume_usage_bytes/px_volume_capacity_bytes)*100",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  { "title": "Volume Latency Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Volume Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "px_volume_vol_read_latency_seconds{volumeid=~\"$volumeid\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "px_volume_vol_write_latency_seconds{volumeid=~\"$volumeid\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(px_volume_iops{volumeid=~\"$volumeid\"}[5m])",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Volume IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "IOPS" }
   ],
   "targets": [
    { "expr": "px_volume_iops", "legendFormat": "{{ volumename }}" }
   ]
  },
  { "title": "Volume Throughput Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Volume Read Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/second" }
   ],
   "targets": [
    {
     "expr": "px_volume_readthroughput{volumeid=~\"$volumeid\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Write Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/second" }
   ],
   "targets": [
    {
     "expr": "px_volume_writethroughput{volumeid=~\"$volumeid\"} ",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  { "title": "Disk Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Disk Read Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Bytes per Second" }
   ],
   "targets": [
    {
     "expr": "irate( px_disk_stats_read_bytes[5m] )",
     "legendFormat": "{{ disk }} - {{ host }} "
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Bytes per Second" }
   ],
   "targets": [
    {
     "expr": "irate( px_disk_stats_write_bytes[5m] )",
     "legendFormat": "{{ disk }} - {{ host }} "
    }
   ]
  }
 ]
}