{
 "title": "Varnish-2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "varnish_instance",
    "label": "Instance",
    "query": {
     "query": "label_values(varnish_up, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "cluster",
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((rate(varnish_main_cache_hit{service=~\"$varnish_instance\"}[5m]) / (rate(varnish_main_cache_hit{service=~\"$varnish_instance\"}[5m]) + rate(varnish_main_cache_miss{service=~\"$varnish_instance\"}[5m]))))"
    }
   ]
  },
  {
   "title": "Frontend Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{service=~\"$varnish_instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_backend_req{service=~\"$varnish_instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_sessions_total{service=~\"$varnish_instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cache Hit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_cache_hit{service=~\"$varnish_instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Loaded VMODs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(varnish_main_vmods{service=~\"$varnish_instance\"})"
    }
   ]
  },
  {
   "title": "Backend Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(varnish_backend_up{service=~\"$varnish_instance\"} == 1))"
    }
   ]
  },
  {
   "title": "Backend Down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(varnish_backend_up{service=~\"$varnish_instance\"} == 0))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(varnish_main_uptime{service=~\"$varnish_instance\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "varnish_version{service=~\"$varnish_instance\"}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{service=~\"$varnish_instance\"}[5m]))",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(irate(varnish_main_backend_req{service=~\"$varnish_instance\"}[5m]))",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(varnish_main_fetch_total{service=~\"$varnish_instance\"})",
     "legendFormat": "fetch total"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(varnish_main_cache_hit{service=~\"$varnish_instance\"}[5m]) / (rate(varnish_main_cache_hit{service=~\"$varnish_instance\"}[5m]) + rate(varnish_main_cache_miss{service=~\"$varnish_instance\"}[5m]))",
     "legendFormat": "cache hit %"
    },
    {
     "expr": "rate(varnish_main_cache_miss{service=~\"$varnish_instance\"}[5m]) / (rate(varnish_main_cache_hit{service=~\"$varnish_instance\"}[5m]) + rate(varnish_main_cache_miss{service=~\"$varnish_instance\"}[5m]))",
     "legendFormat": "cache miss %"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_s_resp_hdrbytes{service=~\"$varnish_instance\"}[5m]) + irate(varnish_main_s_resp_bodybytes{service=~\"$varnish_instance\"}[5m]))",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{service=~\"$varnish_instance\"}[5m]) + irate(varnish_backend_beresp_bodybytes{service=~\"$varnish_instance\"}[5m]))",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{service=~\"$varnish_instance\"}[5m]) + irate(varnish_backend_beresp_bodybytes{service=~\"$varnish_instance\"}[5m])) by (backend)",
     "legendFormat": "backend {{ backend }}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_n_expired{service=~\"$varnish_instance\"}[5m]))",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_moved{service=~\"$varnish_instance\"}[5m]))",
     "legendFormat": "LRU moved"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_nuked{service=~\"$varnish_instance\"}[5m]))",
     "legendFormat": "LRU nuked"
    },
    {
     "expr": "sum(varnish_sma_g_bytes{type=\"s0\", service=~\"$varnish_instance\"})",
     "legendFormat": "mem used"
    }
   ]
  }
 ]
}